services:
  tagsafe-panel:
    image: tagsafe-panel:1.1
    #pull_policy: always
    container_name: tagsafe-control-panel
    restart: always
    ports:
      - "8083:80"
    env_file:
      - ./.env.local